# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 464905d1e67e80970b8beef72cbae018ad8c097a4dffb244a92c914c85c3976d6b6b1f2de8523c93a4bf2f6dfedfb09517c49228edd31fe20a45c4018b4c43ef

test:
  secret_key_base: beb5b591497248764efd78be93ba148276c9deba14e52da2bbaab54b42707ab0cb248e83aaf0e763a692329fdd9bd6b68039dff5e41aca6396f35181c0e1e267

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
